-- 경비 알림(읽음) 상태 테이블 생성
  CREATE TABLE "SYSTEM"."EXPENSE_ITEM_READ_STATUS" 
   (	"ID" NUMBER, 
	"EXPENSE_ITEM_ID" NUMBER NOT NULL ENABLE, 
	"READER_MEMBER_ID" NUMBER NOT NULL ENABLE, 
	"READ_YN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"READ_AT" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 CONSTRAINT "CHK_EXP_READ_YN" CHECK (READ_YN IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "FK_EXP_ITEM_READ_ITEM" FOREIGN KEY ("EXPENSE_ITEM_ID")
	  REFERENCES "SYSTEM"."EXPENSE_ITEMS_INTRANET" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_EXP_ITEM_READ_MEMBER" FOREIGN KEY ("READER_MEMBER_ID")
	  REFERENCES "SYSTEM"."MEMBERS_INTRANET" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE INDEX "SYSTEM"."IDX_EXP_READ_STATUS_ITEM" ON "SYSTEM"."EXPENSE_ITEM_READ_STATUS" ("EXPENSE_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE INDEX "SYSTEM"."IDX_EXP_READ_STATUS_READER" ON "SYSTEM"."EXPENSE_ITEM_READ_STATUS" ("READER_MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE INDEX "SYSTEM"."IDX_EXP_READ_STATUS_READ_YN" ON "SYSTEM"."EXPENSE_ITEM_READ_STATUS" ("READ_YN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE INDEX "SYSTEM"."IDX_EXP_READ_STATUS_READER_YN" ON "SYSTEM"."EXPENSE_ITEM_READ_STATUS" ("READER_MEMBER_ID", "READ_YN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;